apiVersion: apps/v1
kind: Deployment
metadata:
  name: catweb
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catweb
  template:
    metadata:
      labels:
        app: catweb
    spec:
      containers:
      - image: registry.gitlab.com/adess-demos/demo/gitops/catweb-gitops/main:03267de45a8c9ff0d1468b06b8b78379c379e08d
        name: catweb
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: gitlab-registry-credentials
