apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- catweb-ingress.yaml
images:
- name: registry.gitlab.com/adess-demos/demo/gitops/catweb-gitops
  newName: registry.gitlab.com/adess-demos/demo/gitops/catweb-gitops:registry.gitlab.com/adess-demos/demo/gitops/catweb-gitops/main
  newTag: 7bab0df7f0418854303fea3a5ca9b57df7b53a97
- name: registry.gitlab.com/adess-demos/demo/gitops/catweb-gitops/main
  newName: registry.gitlab.com/adess-demos/demo/gitops/catweb-gitops/main
  newTag: b3ba708fe0e1099c05b33aa05d3b23e5b43d71e6
namespace: prod
